<a href="https://colab.research.google.com/github/pb-roshith/matrix-operations/blob/main/matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
m1 = np.array([[2,3], [6,7]])
print(m1)

[[2 3]
 [6 7]]


In [3]:
m1.shape

(2, 2)

In [4]:
m2 = np.array([[10,13], [63,72], [23,66]])
print(m2)

[[10 13]
 [63 72]
 [23 66]]


In [6]:
m2.shape

(3, 2)

In [14]:
ran = np.random.rand(3,4)
print(ran)

[[0.77203756 0.34418853 0.39945547 0.22070019]
 [0.64863642 0.53078084 0.88105297 0.94198671]
 [0.05744786 0.08502773 0.14325718 0.40137727]]


In [15]:
ran2 = np.random.randint(100, size=(3,6))
print(ran2)

[[51 20 70  7 82 96]
 [46 11 79 20 22 64]
 [ 4  1 86 22 61 84]]


In [17]:
m3 = np.ones((2,5))
print(m3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
m4 = np.ones((5,5), dtype=int)
print(m4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
nul = np.zeros((4,4))
print(nul)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
ide = np.eye(5,5)
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
mr = np.random.randint(200, size=(4,4))
t = np.transpose(mr)
print(mr)
print(t)

[[136 175  77 172]
 [ 75  32 192 193]
 [114  73  48 172]
 [165  58 191 171]]
[[136  75 114 165]
 [175  32  73  58]
 [ 77 192  48 191]
 [172 193 172 171]]


In [39]:
mr1 = np.random.randint(200, size=(4,4))
mr2 = np.random.randint(200, size=(4,4))
add1 = np.add(mr1, mr2)
sub1 = np.subtract(mr1, mr2)
mul1 = np.multiply(mr1, mr2)
div1 = np.divide(mr1, mr2)
print(mr1)
print(mr2)

[[188 113 109 192]
 [169  74 171  78]
 [131 156 118 198]
 [136  47  29 116]]
[[ 71 151  63 196]
 [107 133 141 127]
 [156  51 187 175]
 [122   5  71 160]]


In [44]:
print(add1)
print(sub1)
print(mul1)
print(div1)
print(2*mr1)

[[259 264 172 388]
 [276 207 312 205]
 [287 207 305 373]
 [258  52 100 276]]
[[117 -38  46  -4]
 [ 62 -59  30 -49]
 [-25 105 -69  23]
 [ 14  42 -42 -44]]
[[13348 17063  6867 37632]
 [18083  9842 24111  9906]
 [20436  7956 22066 34650]
 [16592   235  2059 18560]]
[[2.64788732 0.74834437 1.73015873 0.97959184]
 [1.57943925 0.55639098 1.21276596 0.61417323]
 [0.83974359 3.05882353 0.63101604 1.13142857]
 [1.1147541  9.4        0.4084507  0.725     ]]
[[376 226 218 384]
 [338 148 342 156]
 [262 312 236 396]
 [272  94  58 232]]
